### ISSUE TITLE
Make a widget on the home screen.

### ISSUE THREAD

**Issue by FazziCLAY** [FazziCLAY/OpenToday#12]

**Comment by FazziCLAY** [comment]
The widget should be in **com**.fazziclay.opentoday

**Comment by lucile98-ode** [comment]
Hello FazziClay, 
Did you need any help ? With @xenom34 we want to help you on this issue :)

**Comment by FazziCLAY** [comment]
> Hello FazziClay, Did you need any help ? With @xenom34 we want to help you on this issue :)

Yes

**Comment by FazziCLAY** [comment]
Impossible because RemoteView not allowed RecycleList's and more
