### ISSUE TITLE
Settings (swipe actions) aren't saved.

### ISSUE THREAD

**Issue by pacjo** [FazziCLAY/OpenToday#2]
I noticed that settings such as swipe actions aren't saved. 

Device information:
OS: Android 12, crDroid 8.9
Device: Redmi Note 10 Pro

Below is a gif showing the issue:
![recording](https://user-images.githubusercontent.com/56438628/197240709-c6c84fb2-c1c0-47e1-80e5-b5498e564b2b.gif)

**Comment by FazziCLAY** [comment]
I don't have enough time right now, but this will be fixed in the next version!

If you are familiar with java, you can create a pull request with the correction of this bug

**Comment by pacjo** [comment]
> I don't have enough time right now, but this will be fixed in the next version!

Sure, take your time 


> If you are familiar with java, you can create a pull request with the correction of this bug

Sorry, but I know nothing about android development. Maybe in the future, but it would probably be with kotlin or dart.

**Comment by lucile98-ode** [comment]
Hello everyone,
With @xenom34 we would like to try to participate in this issue.
Is it possible to be assigned on it?
Thanks (:

**Comment by FazziCLAY** [comment]
> Hello everyone, With @xenom34 we would like to try to participate in this issue. Is it possible to be assigned on it? Thanks (:

I have already fixed this problem in one of the commits, it remains to wait for the release of the release
if you want to help the project, just create pull requests

**Comment by FazziCLAY** [comment]
// fixed in local commit. Wait...

**Comment by FazziCLAY** [comment]
# Fixed in 0.9.8 (2022.11.01)
