### ISSUE TITLE
Allow setting default item type

### ISSUE THREAD

**Issue by pacjo** [FazziCLAY/OpenToday#22]
I would like to be able to change default item type from text to checkbox, so that I would be able to use `Type here` input at the bottom of the app instead of going into `Item` -> `Checkbox` everytime I want to add something.

![Screenshot_20230207-171237_OpenToday](https://user-images.githubusercontent.com/56438628/217300222-42aabcfe-07ef-458e-a228-82f5bb87fada.png)
Make type of this ^ changeable

**Comment by FazziCLAY** [comment]
Temporarily use pressing the "send" button
When clamped, there will be a choice of type

**Comment by FazziCLAY** [comment]
I'll fix it, thanks for your active interest :)

**Comment by pacjo** [comment]
> Temporarily use pressing the "send" button (Hold button) When clamped, there will be a choice of type

Didn't know about, thanks.
