### ISSUE TITLE
Allow setting custom save location (for synchronization purposes)

### ISSUE THREAD

**Issue by pacjo** [FazziCLAY/OpenToday#24]
Hi (me again), 
I've been thinking, that it would be nice to have an ability to set a custom location for app's data (something like: `/storage/emulated/0/OpenToday`). Than it would be possible to synchronise this directory with external program (like syncthing).
This would allow for having synchronised notes on multiple devices without too much work.

**Comment by pacjo** [comment]
Just checked and found files in `/storage/emulated/0/Android/data/com.fazziclay.opentoday/files`. Would synchronising this with other device result in the same notes on both devices?

**Comment by FazziCLAY** [comment]
> Just checked and found files in `/storage/emulated/0/Android/data/com.fazziclay.opentoday/files`. Would synchronising this with other device result in the same notes on both devices?

Yes, but the application must be completely unloaded from RAM for such a "focus"

**Comment by pacjo** [comment]
> application must be completely unloaded from RAM

ok, but what would happen if it wasn't unloaded and files would be synced to another device? Would it just result in an older version of those, or can something go wrong and result in (let's say) data loss?

**Comment by FazziCLAY** [comment]
@pacjo This will result in older data
by the way, it is enough to replace only 1 file, `item_data.gz`

**Comment by FazziCLAY** [comment]
I can't make an external folder, because I don't know how (initially I wanted to)

**Comment by pacjo** [comment]
> I can't make an external folder, because I don't know how (initially I wanted to)

That's no problem, for no I can try with `item_data.gz`.

**Comment by pacjo** [comment]
I just checked and even with syncthing in root mode it can't acces the Android/data directories, so no synchronization for now.

**Comment by FazziCLAY** [comment]
I'm really sorry, but it's unlikely that I will be able to implement this, but if someone can, I will gladly accept these changes
