### ISSUE TITLE
fastlane changelog much too long

### ISSUE THREAD

**Issue by IzzySoft** [FazziCLAY/OpenToday#56]
Fastlane changelogs are limited to 500 chars. Your latest one has more than 2k, and thus will have its content trucated at char 500 (looking weird). Please take care to stay within the limits :wink: For Reference, here's my [Fastlane Cheat Sheet](https://gitlab.com/-/snippets/1895688). Thanks!

**Comment by FazziCLAY** [comment]
Okay, thanks for this notification!

**Comment by IzzySoft** [comment]
Thanks! Pulled it in manually (had removed the "big one" before), so it will show up again with the next sync.
